apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: "ack-api"
spec:
  name: "ack-api"
  protocolType: HTTP

---

apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: "ack-integration"
spec:
  apiRef:
    from:
      name: "ack-api"
  integrationType: HTTP_PROXY
  integrationURI: "https://httpbin.org/get"
  integrationMethod: GET
  payloadFormatVersion: "1.0"

---

apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  name: "ack-route"
spec:
  apiRef:
    from:
      name: "ack-api"
  routeKey: "GET /ack-route-key"
  targetRef:
    from:
      name: "ack-integration"

---

apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Stage
metadata:
  name: "ack-stage"
spec:
  apiRef:
    from:
      name: "ack-api"
  stageName: "ack-stage"
  autoDeploy: true
  description: "auto deployed stage for ack-api"
